name: SwiftUIClaudeClient
options:
  bundleIdPrefix: com.dbgventures.claudecode
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
    visionOS: "1.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  Starscream:
    url: https://github.com/daltoniam/Starscream
    majorVersion: 4.0.0

targets:
  # iOS App
  SwiftUIClaudeClient:
    type: application
    platform: iOS
    sources:
      - path: Shared
        excludes:
          - "**/*.md"
      - path: iPadOS
        excludes:
          - "**/*.md"
    resources:
      - iPadOS/Resources
    dependencies:
      - package: Starscream
    info:
      path: iPadOS/Info.plist
      properties:
        CFBundleDisplayName: "Claude Code"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - armv7
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSExceptionDomains:
            localhost:
              NSExceptionAllowsInsecureHTTPLoads: true
    settings:
      PRODUCT_NAME: "Claude Code"
      PRODUCT_BUNDLE_IDENTIFIER: "com.dbgventures.claudecode.ios"
      SWIFT_VERSION: "5.9"
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      TARGETED_DEVICE_FAMILY: "2" # iPad only
      SUPPORTS_MACCATALYST: false
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""

schemes:
  SwiftUIClaudeClient:
    build:
      targets:
        SwiftUIClaudeClient: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release